# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c695ea00c7c1aa5e12c216435ffbd31c4037b92636f62ae6755ee91591a3304eae04f427265f7113d4b29819c6c28926bcaa7cfd3ef87b0ebd9fdd3987f61ac

test:
  secret_key_base: 26c7c3e81ee6a4abcfdeb1b857bfb5c79ee94f64eb1aeccb45819bd9aab56e2eadb32f986efc6e20c43309cf3042674158b330d98d9c8178e97f065f8f7a6bd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
